targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
        options:
          # build_extensions takes a source pattern and if it matches it will transform the output
          # to your desired path. The default behaviour is to the .mocks.dart file to be in the same
          # directory as the source .dart file. As seen below this is customizable, but the generated
          # file must always end in `.mocks.dart`. 
          build_extensions:
            '^test/{{}}.dart' : 'test/mocks/{{}}.mocks.dart' 
